name: build-istio-proxy

on:
  push:
    tags:
      - istio-proxy

jobs:
  amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: docker buildx bake -f istio-proxy-bake.hcl istio-proxy-amd64 --push
  arm64:
    runs-on: ubuntu-latest
    timeout-minutes: 1800
    steps:
      - uses: actions/checkout@v2
      - uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: docker buildx bake -f istio-proxy-bake.hcl istio-proxy-arm64 --push